"use client";
import Link from "next/link";
import { useState } from "react";
import { LogOut, Menu as MenuIcon, Settings as SettingsIcon, X } from "lucide-react";
import { LiveCounter } from "./LiveCounter";
import { logoutAction } from "@/app/login/actions";
import { useAuth } from "@/components/auth/AuthProvider";

export function TopNav({ onMenuClick, menuOpen = false }: { onMenuClick?: () => void; menuOpen?: boolean }) {
  return <header className="flex min-h-12 shrink-0 items-center border-b border-line bg-canvas px-2 sm:px-3 md:px-4"><button type="button" onClick={onMenuClick} aria-label={menuOpen ? "Close menu" : "Open menu"} aria-expanded={menuOpen} aria-controls="mobile-navigation" className="mr-2 inline-flex h-11 w-11 cursor-pointer items-center justify-center text-fg-muted transition-colors hover:bg-surface-1 hover:text-fg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal/70 md:hidden">{menuOpen ? <X size={16} /> : <MenuIcon size={16} />}</button><div className="flex items-center gap-3"><Logo /><span className="hidden font-mono text-xs uppercase tracking-[0.18em] text-fg-muted sm:inline">blackwatch</span></div><div className="ml-auto flex items-center gap-1 sm:gap-2 md:gap-4"><LiveCounter /><Link href="/settings" aria-label="Settings" className="inline-flex h-11 w-11 cursor-pointer items-center justify-center text-fg-muted transition-colors hover:bg-surface-1 hover:text-fg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal/70 md:h-8 md:w-8"><SettingsIcon size={15} strokeWidth={1.5} /></Link><AccountMenu /></div></header>;
}
function Logo() { return <span aria-hidden className="grid h-5 w-5 place-items-center border border-signal text-[9px] font-medium leading-none text-signal">BW</span>; }
function AccountMenu() { const [open, setOpen] = useState(false); const { user, role, loading } = useAuth(); const initials = (user ?? "??").slice(0, 2).toUpperCase(); const viewer = !loading && role === "viewer"; return <div className="relative flex items-center gap-2">{viewer && <span className="hidden border border-line px-1.5 py-0.5 font-mono text-[9px] uppercase text-fg-muted sm:inline">viewer</span>}<button type="button" onClick={() => setOpen((value) => !value)} aria-label="Account" aria-haspopup="menu" aria-expanded={open} className="grid h-11 w-11 cursor-pointer place-items-center rounded-sm border border-line bg-surface-1 font-mono text-[10px] text-fg-muted transition-colors hover:border-signal focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal/70 md:h-8 md:w-8">{initials}</button>{open && <div role="menu" className="absolute right-0 top-12 z-50 min-w-52 border border-line bg-surface-1 p-1 shadow-xl md:top-9"><div className="px-3 py-2"><div className="truncate text-sm text-fg">{user ?? "unknown"}</div><div className="font-mono text-[10px] uppercase text-fg-subtle">{loading ? "…" : role}</div></div><Link href="/settings" onClick={() => setOpen(false)} className="flex min-h-11 cursor-pointer items-center gap-2 px-3 py-2 text-sm text-fg-muted transition-colors hover:bg-surface-2 hover:text-fg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal/70"><SettingsIcon size={15} /> Settings</Link><form action={logoutAction}><button type="submit" onClick={() => setOpen(false)} className="flex min-h-11 w-full cursor-pointer items-center gap-2 px-3 py-2 text-left text-sm text-fg-muted transition-colors hover:bg-surface-2 hover:text-fg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal/70"><LogOut size={15} /> Sign out</button></form></div>}</div>; }
